#!/bin/bash

echo "Installing..."
echo "Installing Dependencies"
pip3 install -r dependencies
echo "Copying main.py and token To /usr/local/bin"
cp main.py /usr/local/bin
cp token /usr/local/bin
echo "python3 main.py \$1 \$2" >> /usr/local/bin/run
chmod 755 /usr/local/bin/run

ln -s /usr/local/bin/run /usr/local/bin/gitprep
echo "Done!"

